file_format: "1"
id: tbk_corne
name: Tbk-corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - corne_left
  - corne_right
